# Generated by Django 5.0.8 on 2026-09-19 11:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Месяц')),
                ('hall_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Сумма, которую нужно оплатить залу за месяц. Вносится админом.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Счёт за зал')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Месяц закрыт')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Месяц',
                'verbose_name_plural': 'Месяцы',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('method', models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод'), ('other', 'Другое')], default='transfer', max_length=16, verbose_name='Способ оплаты')),
                ('paid_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата оплаты')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждён'), ('rejected', 'Отклонён')], default='pending', max_length=16, verbose_name='Статус')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
                'ordering': ['-paid_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Назначение')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('spent_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата траты')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='Кто оплатил')),
            ],
            options={
                'verbose_name': 'Общая трата',
                'verbose_name_plural': 'Общие траты',
                'ordering': ['-spent_on'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время игры')),
                ('place', models.CharField(blank=True, max_length=120, verbose_name='Место')),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Общая стоимость игры. Делится между участниками.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Стоимость игры')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('players', models.ManyToManyField(blank=True, help_text='Игроки, которые участвовали и должны скинуться.', related_name='games', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['-played_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='month',
            constraint=models.UniqueConstraint(fields=('year', 'month'), name='unique_year_month'),
        ),
        migrations.AddConstraint(
            model_name='month',
            constraint=models.CheckConstraint(check=models.Q(('month__gte', 1), ('month__lte', 12)), name='month_between_1_and_12'),
        ),
        migrations.AddField(
            model_name='game',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='tracker.month', verbose_name='Месяц'),
        ),
        migrations.AddField(
            model_name='expense',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='tracker.month', verbose_name='Месяц'),
        ),
        migrations.AddField(
            model_name='payment',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tracker.game', verbose_name='Игра'),
        ),
        migrations.AddField(
            model_name='payment',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Игрок'),
        ),
    ]
