# Generated by Django 5.0.8 on 2026-09-19 20:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('method', models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод'), ('other', 'Другое')], default='transfer', max_length=16, verbose_name='Способ оплаты')),
                ('paid_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата оплаты')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждён'), ('rejected', 'Отклонён')], default='pending', max_length=16, verbose_name='Статус')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='tracker.expense', verbose_name='Трата')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_contributions', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Взнос на трату',
                'verbose_name_plural': 'Взносы на траты',
                'ordering': ['-paid_on', '-created_at'],
            },
        ),
    ]
