# Generated by Django 5.0.8 on 2026-09-21 17:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_expensecontribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='starting_capital',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Остаток денег на начало месяца (например, с прошлого месяца).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Стартовый капитал'),
        ),
    ]
